name: Text Typos or Improvements
description: Any typo fixes or improvement suggestions for campaign dialog, unit descriptions, or other game text.
labels: ['Prose']

body:
  - type: markdown
    attributes:
      value: >
        **Note:** The house style of Wesnoth uses a good many words and constructions that are archaic, poetic,
        or dialectal. If you speak modern English as a second language you may incorrectly read these as errors.
        Please see [NotSpellingMistakes](https://wiki.wesnoth.org/NotSpellingMistakes) for a list of things you
        will encounter that may look like spelling or usage errors but are not.

        Note that the mainline campaigns are now using correct typography, including sexed quotes and en and em
        dashes. These will appear as three byte sequences if you are not using a viewer that supports UTF-8.

  - type: input
    id: language
    attributes:
      label: Language
      description: What language does the typo appear in?

  - type: input
    id: location
    attributes:
      label: Source
      description: Where does the typo appear? If part of a campaign, specify the scenario.
    validations:
      required: true

  - type: textarea
    id: original_text
    attributes:
      label: Original Text
      description: Quote the text verbatim. You can use `**bold**` to highlight the issue.
    validations:
      required: true

  - type: textarea
    id: new_text
    attributes:
      label: Proposed Change
